apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-5lxp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-5lxp
    app.kubernetes.io/part-of: load-app-a6a81d43-18d4-41e0-bc42-787875a39105
  name: devfile-sample-5lxp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-5lxp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-5lxp
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-67-tenant/load-app-a6a81d43-18d4-41e0-bc42-787875a39105/devfile-sample-5lxp@sha256:e5cd03f91fe9e69d87e1a5f6282140403cb185951178e09c6dca1ffb9a717ce9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
