apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-5lxp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-5lxp
    app.kubernetes.io/part-of: load-app-a6a81d43-18d4-41e0-bc42-787875a39105
  name: devfile-sample-5lxp
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-5lxp
status:
  loadBalancer: {}
